language: node_js

node_js:
  - "5"

before_script:
  - "export DISPLAY=:0.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_install:
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :0 -ac -screen 0 1280x1024x16"

after_success:
  - npm i coveralls
  - cat ./coverage/*/lcov.info | coveralls
